/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHeader {
    }
    interface AppHomePage {
    }
    interface AppProfilePage {
        "name": string;
    }
    interface AppRoot {
    }
    interface HeaderNavigation {
    }
    interface WebComponents {
    }
}
declare global {
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomePageElement extends Components.AppHomePage, HTMLStencilElement {
    }
    var HTMLAppHomePageElement: {
        prototype: HTMLAppHomePageElement;
        new (): HTMLAppHomePageElement;
    };
    interface HTMLAppProfilePageElement extends Components.AppProfilePage, HTMLStencilElement {
    }
    var HTMLAppProfilePageElement: {
        prototype: HTMLAppProfilePageElement;
        new (): HTMLAppProfilePageElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHeaderNavigationElement extends Components.HeaderNavigation, HTMLStencilElement {
    }
    var HTMLHeaderNavigationElement: {
        prototype: HTMLHeaderNavigationElement;
        new (): HTMLHeaderNavigationElement;
    };
    interface HTMLWebComponentsElement extends Components.WebComponents, HTMLStencilElement {
    }
    var HTMLWebComponentsElement: {
        prototype: HTMLWebComponentsElement;
        new (): HTMLWebComponentsElement;
    };
    interface HTMLElementTagNameMap {
        "app-header": HTMLAppHeaderElement;
        "app-home-page": HTMLAppHomePageElement;
        "app-profile-page": HTMLAppProfilePageElement;
        "app-root": HTMLAppRootElement;
        "header-navigation": HTMLHeaderNavigationElement;
        "web-components": HTMLWebComponentsElement;
    }
}
declare namespace LocalJSX {
    interface AppHeader {
    }
    interface AppHomePage {
    }
    interface AppProfilePage {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface HeaderNavigation {
    }
    interface WebComponents {
    }
    interface IntrinsicElements {
        "app-header": AppHeader;
        "app-home-page": AppHomePage;
        "app-profile-page": AppProfilePage;
        "app-root": AppRoot;
        "header-navigation": HeaderNavigation;
        "web-components": WebComponents;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home-page": LocalJSX.AppHomePage & JSXBase.HTMLAttributes<HTMLAppHomePageElement>;
            "app-profile-page": LocalJSX.AppProfilePage & JSXBase.HTMLAttributes<HTMLAppProfilePageElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "header-navigation": LocalJSX.HeaderNavigation & JSXBase.HTMLAttributes<HTMLHeaderNavigationElement>;
            "web-components": LocalJSX.WebComponents & JSXBase.HTMLAttributes<HTMLWebComponentsElement>;
        }
    }
}
